GDV-489: Add legend component for visible layers
openearth/coclico-static pull request #11
Opened 2022-05-12 10:24 UTC by IoannaMi

TODO: read values for legend from stac

2022-05-30 08:33 UTC, CindyvdVries requested changes
The tests for the store should be updated and please run npm run lint -- --fix!

I don't see it working, is this dependent on a certain version of the coclico-data repo?

2022-05-30 08:33 UTC, CindyvdVries commented on src/components/DataLayersCard.vue
> +          //TODO: check if there is a better way. I need the layerId to check if the layer is in the activeMapboxLayers
as in using the params from the router?? (we do this in a few other places in the dgds-front-end code as well)
this is being done also in a few places in the coclico code I see, maybe make a central action in the store or something?

2022-05-30 08:33 UTC, CindyvdVries commented on src/store/map/index.js
> +import matchLayerIdToProperties from '@/lib/match-layerId-to-properties.js'
layer-id (mixup camelCase and snake_case)

2022-05-30 08:33 UTC, CindyvdVries commented on src/store/map/index.js
> +      //remove mapboxlayer in order to re-add it with the new colors
update paint of existing layer?

2022-06-01 12:56 UTC, IoannaMi commented
> The tests for the store should be updated and please run npm run lint -- --fix!



> The tests for the store should be updated and please run npm run lint -- --fix!
> 
> I don't see it working, is this dependent on a certain version of the coclico-data repo?

Yep it is dependent on certain version indeed. Still waiting for the properties that contains the colors to be on the live version.

2022-06-01 12:58 UTC, IoannaMi commented
> > The tests for the store should be updated and please run npm run lint -- --fix!
> 
> > The tests for the store should be updated and please run npm run lint -- --fix!
I started at the end of the previous sprint working on the tests but in another branch. Not in this one.
> > I don't see it working, is this dependent on a certain version of the coclico-data repo?
> 
> Yep it is dependent on certain version indeed. Still waiting for the properties that contains the colors to be on the live version. It works only locally at this moment if you change to this certion version of the coclico-data repo

2022-06-07 09:00 UTC, merged